version: '3'
services:
 
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 600 50 --appendonly yes
      - RIAUTHPROMPT=1

    volumes:
      - redis_data:/data
    # Removed the ports section to not expose directly unless necessary

volumes:
  redis_data:
  config:  # Volume for SWAG configuration